In [2]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data"

In [3]:
# モジュールのインポート
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
#jupyter用のおまじない
%matplotlib inline

In [5]:
#課題
#　urlを使ってcsvファイルの読み込みを行なってください
#上から5件分の表示をしてください

# df = pd.read_csv(url, header=None)
# df.head()

#上記だけだと、元のcsvファイルがカンマ区切りではなく、スペース区切りなので、全て一つのファイルになってしまう

df = pd.read_csv(url, header=None, sep="\s+")
df.head()

0     1     2   3      4      5     6       7   8      9     10  \
0  0.00632  18.0  2.31   0  0.538  6.575  65.2  4.0900   1  296.0  15.3   
1  0.02731   0.0  7.07   0  0.469  6.421  78.9  4.9671   2  242.0  17.8   
2  0.02729   0.0  7.07   0  0.469  7.185  61.1  4.9671   2  242.0  17.8   
3  0.03237   0.0  2.18   0  0.458  6.998  45.8  6.0622   3  222.0  18.7   
4  0.06905   0.0  2.18   0  0.458  7.147  54.2  6.0622   3  222.0  18.7   

       11    12    13  
0  396.90  4.98  24.0  
1  396.90  9.14  21.6  
2  392.83  4.03  34.7  
3  394.63  2.94  33.4  
4  396.90  5.33  36.2

In [6]:
df.columns = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
              'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
#一番右端が価格の中央値であり、出力y
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [7]:
#課題
#入力Xと出力yの切り分けを行う

# X = df[['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
#               'TAX', 'PTRATIO', 'B', 'LSTAT']]
# y = df[["MEDV"]]

#現在はpandasの変数みたいな形なので、numpyにしてあげないといけない
#そのために、.valuesをつける。pandas（パンダス）でデータの切り分けをして、numpy（ナムパイ）で解析
X = df[['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
              'TAX', 'PTRATIO', 'B', 'LSTAT']].values
y = df[["MEDV"]].values

# scikit-learnによる実装

In [8]:
from sklearn import linear_model

In [9]:
#インスタンス化（LinearRegression ですでにある重回帰分析するモデルを呼び出した）
reg = linear_model.LinearRegression()

#モデルの学習
reg.fit(X,y)

/usr/local/lib/python3.6/site-packages/scipy/linalg/basic.py:1226: RuntimeWarning: internal gelsd driver lwork query error, required iwork dimension not returned. This is likely the result of LAPACK bug 0038, fixed in LAPACK 3.2.2 (released July 21, 2010). Falling back to 'gelss' driver.
  warnings.warn(mesg, RuntimeWarning)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [25]:
#reshapeがないとエラーになる
x = X[0].reshape(1,-1)
print(x)

[[6.320e-03 1.800e+01 2.310e+00 0.000e+00 5.380e-01 6.575e+00 6.520e+01
  4.090e+00 1.000e+00 2.960e+02 1.530e+01 3.969e+02 4.980e+00]]


In [11]:
#価格を予想
reg.predict(x)

array([[30.00384338]])

In [12]:
#実際の家賃を確認(直線で確認する重回帰分析はせいぜいこんなもん)
#注意点としては、X,yのうちの、60パーセントや70パーセントを訓練データ（train data)としてモデルに学習させ
# 残りのデータで検証（test)する
y[0]

array([24.])

In [13]:
# 訓練用データ(train)と検証用データ(test)に分割
from sklearn.cross_validation import train_test_split
# 訓練データ(train)と検証データ(test)の分割
# 「test_size=0.3」は30%を検証用データに使用すると宣言
# 自動的に70%が訓練用になる
#random_state=0 で70パーセント選ぶさいにランダムに選んでくれるようにするが
# 機械学習はデータ・ドリブンなので、乱数の取り方を指定しないと、毎回そのモデルの学習データが異なってしまい、
# 精度がバラバラになってしまうため、乱数の取り方の指定が必要
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

/usr/local/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [14]:
#インスタンスか
reg = linear_model.LinearRegression()

#訓練データX_train,y_train
#モデルの学習
reg.fit(X,y)



LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [15]:
x = X_test[0].reshape(1,-1)
#reshape　で１行13列でもいい、pandasだとただの配列で行列になっていないためエラーになってしまう
# また、-1にすると勝手に直してくれるので-1は便利（１行12列にしてくれている、
# 2、-1にすると１２個データがあって２行と決めるから勝手に4列にしてくれる）
reg.predict(x)

array([[24.25249073]])

In [16]:
y_test[0]

array([22.6])

In [17]:
#決定係数（重回帰分析をした際の精度みたいなもん）
reg.score(X_test,y_test)

0.689631319137092